import { Category, Question } from "./types";

const raw: Array<[Category, string]> = [
  ["Bromas", "Seguro eres así con todas."], ["Provocaciones", "Tienes cara de que te crees demasiado."], ["Bromas", "Pensé que eras más divertido."], ["Presión social", "¿Siempre necesitas llamar la atención?"], ["Conversación", "Eres más tímido de lo que aparentas."], ["Improvisación", "A ver, sorpréndeme."], ["Conversación", "Hablas bastante."], ["Difíciles", "¿Por qué debería seguir hablando contigo?"], ["Difíciles", "No pareces mi tipo."], ["Provocaciones", "Te estás esforzando demasiado."],
  ["Bromas", "¿Eso fue lo mejor que se te ocurrió?"], ["Conversación", "Tienes una energía curiosa."], ["Provocaciones", "¿Siempre eres tan intenso?"], ["Presión social", "Todos te están mirando, ¿te pones nervioso?"], ["Improvisación", "Véndeme tu mejor cualidad en diez segundos."], ["Seguridad", "¿De verdad crees que vas a impresionarme?"], ["Difíciles", "Me parece que no sabes escuchar."], ["Bromas", "Tu cara dice que tienes una historia rara."], ["Conversación", "¿Qué haces cuando no estás intentando caer bien?"], ["Provocaciones", "Estás muy confiado para conocernos tan poco."],
  ["Presión social", "Tus amigos seguramente te describen distinto."], ["Improvisación", "Defiende una opinión que no compartes."], ["Seguridad", "¿Qué te hace pensar que tenemos química?"], ["Bromas", "Eso sonó mejor en tu cabeza, ¿no?"], ["Difíciles", "No estoy segura de que seas tan interesante."], ["Conversación", "¿Qué pregunta nunca te hacen y te gustaría responder?"], ["Provocaciones", "Pareces demasiado acostumbrado a ganar."], ["Bromas", "Te doy un seis, siendo generosa."], ["Presión social", "No cambies de tema ahora."], ["Improvisación", "Convénceme de que hoy valió la pena salir."],
  ["Seguridad", "Me parece que te subestimas."], ["Difíciles", "¿Qué harías si te dijera que me aburrí?"], ["Conversación", "¿Qué detalle te delata cuando alguien te gusta?"], ["Bromas", "Tu primera impresión no fue exactamente inolvidable."], ["Provocaciones", "¿Te molesta que tenga razón?"], ["Presión social", "Responde sin pensarlo demasiado."], ["Improvisación", "Inventa un titular sobre tu vida."], ["Seguridad", "No pareces alguien fácil de sorprender."], ["Difíciles", "¿Qué estás evitando decir?"], ["Conversación", "¿Qué te da vergüenza admitir que te gusta?"],
  ["Bromas", "Te ves como alguien que llega tarde a todo."], ["Provocaciones", "¿Esto es tu personalidad o estás actuando?"], ["Presión social", "El silencio también es una respuesta."], ["Improvisación", "Descríbete sin usar adjetivos."], ["Seguridad", "¿Qué tienes tú que no tenga cualquiera?"], ["Difíciles", "No me has dado ningún motivo para recordarte."], ["Conversación", "¿Qué fue lo último que te hizo reír de verdad?"], ["Bromas", "Pareces peligroso… para elegir restaurante."], ["Provocaciones", "¿Te cuesta aceptar un no?"], ["Presión social", "Ahora dilo mirando a los ojos."],
  ["Improvisación", "Haz que una mala idea suene irresistible."], ["Seguridad", "¿Qué parte de ti estás escondiendo?"], ["Difíciles", "¿Qué pasaría si dejáramos de hablar?"], ["Conversación", "¿En qué tema podrías hablar durante horas?"], ["Bromas", "No sé si reírme o pedir contexto."], ["Provocaciones", "Tienes una opinión para todo."], ["Presión social", "¿Puedes mantener esa seguridad cinco minutos?"], ["Improvisación", "Crea una excusa para desaparecer mañana."], ["Seguridad", "¿Por qué debería confiar en ti?"], ["Difíciles", "Me parece que buscas aprobación."],
  ["Conversación", "¿Qué te hace bajar la guardia?"], ["Bromas", "Eso fue adorablemente torpe."], ["Provocaciones", "¿También discutes contigo mismo?"], ["Presión social", "No puedes responder con otra pregunta."], ["Improvisación", "Vende algo que nadie necesita."], ["Seguridad", "¿Qué cumplido te cuesta creer?"], ["Difíciles", "¿Qué parte de esta conversación te incomoda?"], ["Conversación", "¿Qué te gustaría que la gente entendiera de ti?"], ["Bromas", "Pareces más simpático por mensaje."], ["Provocaciones", "No te esfuerces tanto en parecer relajado."],
  ["Presión social", "Di lo primero que se te venga a la cabeza."], ["Improvisación", "Defiende por qué eres una buena idea."], ["Seguridad", "¿Qué harías si nadie pudiera juzgarte?"], ["Difíciles", "¿Qué mentira piadosa dices con frecuencia?"], ["Conversación", "¿Qué conversación nunca olvidas?"], ["Bromas", "Creo que tu ego llegó antes que tú."], ["Provocaciones", "¿Te gusta tener siempre la última palabra?"], ["Presión social", "Todos esperan una respuesta brillante."], ["Improvisación", "Explica tu día como si fuera una película."], ["Seguridad", "¿Qué te hace diferente de verdad?"],
  ["Difíciles", "¿Qué no estás dispuesto a admitir?"], ["Conversación", "¿Qué te pone de buen humor instantáneamente?"], ["Bromas", "Tu sentido del humor necesita vacaciones."], ["Provocaciones", "¿Esto es confianza o negación?"], ["Presión social", "No tienes mucho tiempo para pensarlo."], ["Improvisación", "Cambia mi opinión sobre ti."], ["Seguridad", "¿Qué parte de tu vida te enorgullece?"], ["Difíciles", "¿Qué supones de mí que no deberías?"], ["Conversación", "¿Qué pregunta te gustaría hacerme?"], ["Bromas", "Pareces el protagonista de una anécdota ajena."],
  ["Provocaciones", "¿Te consideras difícil de leer?"], ["Presión social", "Ahora responde con total honestidad."], ["Improvisación", "Cuenta una historia usando tres palabras."], ["Seguridad", "¿Cuál es tu mejor argumento?"], ["Difíciles", "¿Qué harías para caerme bien?"], ["Conversación", "¿Cuándo fue la última vez que cambiaste de opinión?"], ["Bromas", "Eso explica muchas cosas."], ["Provocaciones", "¿Te ofende que no te tome en serio?"], ["Presión social", "No puedes editar tu respuesta."], ["Improvisación", "Haz una promesa que puedas cumplir hoy."]
];

export const questions: Question[] = raw.map(([category, text], index) => ({ id: `q-${index + 1}`, category: category as Exclude<Category, "Todas">, text }));

export function pickQuestions(category: Category, count: number): Question[] {
  const pool = category === "Todas" ? questions : questions.filter((question) => question.category === category);
  return [...pool].sort(() => Math.random() - 0.5).slice(0, Math.min(count, pool.length));
}
