import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';
import '../application/arena_controller.dart';
import '../domain/entities/arena_entities.dart';
import '../../../core/theme/arena_theme.dart';

class ArenaApp extends ConsumerWidget {
  const ArenaApp({super.key});
  @override Widget build(BuildContext context, WidgetRef ref) { return MaterialApp(title: 'Shit Test Arena', debugShowCheckedModeBanner: false, theme: buildArenaTheme(), home: const ArenaHomePage()); }
}

class ArenaHomePage extends ConsumerStatefulWidget { const ArenaHomePage({super.key}); @override ConsumerState<ArenaHomePage> createState() => _ArenaHomePageState(); }
class _ArenaHomePageState extends ConsumerState<ArenaHomePage> {
  final nickname = TextEditingController(); final code = TextEditingController();
  bool joining = false;
  @override Widget build(BuildContext context) { final state = ref.watch(arenaControllerProvider); final room = state.valueOrNull; return Scaffold(body: Container(decoration: const BoxDecoration(gradient: RadialGradient(center: Alignment.topRight, radius: 1.2, colors: [Color(0xff27101e), Color(0xff09090b), Color(0xff09090b)])), child: SafeArea(child: Center(child: ConstrainedBox(constraints: const BoxConstraints(maxWidth: 720), child: Padding(padding: const EdgeInsets.all(24), child: room == null ? _home(context, state) : _room(context, room))))))); }
  Widget _home(BuildContext context, AsyncValue state) => Column(mainAxisAlignment: MainAxisAlignment.center, crossAxisAlignment: CrossAxisAlignment.stretch, children: [const Text('SHIT\nTEST\nARENA.', style: TextStyle(fontSize: 64, fontWeight: FontWeight.w900, height: .85)), const SizedBox(height: 32), TextField(controller: nickname, maxLength: 20, decoration: const InputDecoration(labelText: 'Nickname')), const SizedBox(height: 12), if (joining) TextField(controller: code, maxLength: 5, textCapitalization: TextCapitalization.characters, decoration: const InputDecoration(labelText: 'Código de sala')), const SizedBox(height: 12), FilledButton(onPressed: () { final name = nickname.text.trim(); if (name.isEmpty) return; if (joining) { ref.read(arenaControllerProvider.notifier).join(code.text.trim(), name); } else { ref.read(arenaControllerProvider.notifier).create(nickname: name, seconds: 10, rounds: 10, category: 'Todas'); } }, child: Text(joining ? 'ENTRAR A SALA' : 'CREAR SALA')), TextButton(onPressed: () => setState(() => joining = !joining), child: Text(joining ? 'Volver a crear sala' : 'Unirse con código')), if (state.hasError) Text('${state.error}', style: const TextStyle(color: Colors.redAccent))]);
  Widget _room(BuildContext context, ArenaRoom room) { final controller = ref.read(arenaControllerProvider.notifier); final isHost = room.hostId == controller.viewerId; final round = room.activeRound; return Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Text('SALA ${room.code}', style: const TextStyle(fontSize: 30, fontWeight: FontWeight.w800)), const SizedBox(height: 24), ...room.participants.map((p) => ListTile(leading: Icon(p.isHost ? Icons.workspace_premium : Icons.circle, color: const Color(0xffd7ff54)), title: Text(p.nickname), trailing: p.isHost ? const Text('HOST') : null)), const Divider(), if (room.status == RoomStatus.waiting && isHost) FilledButton(onPressed: controller.start, child: const Text('COMENZAR PARTIDA')), if (room.status == RoomStatus.waiting && !isHost) const Center(child: Text('ESPERANDO AL HOST...')), if (round != null && room.status == RoomStatus.answering) _answer(context, controller, round), if (round != null && room.status == RoomStatus.revealing) ...[Text('RONDA ${round.number}', style: const TextStyle(fontSize: 20)), Text('“${round.question.text}”'), const SizedBox(height: 12), if (isHost) FilledButton(onPressed: controller.nextRound, child: const Text('SIGUIENTE SHIT TEST'))]]); }
  Widget _answer(BuildContext context, ArenaController controller, ArenaRound round) { final input = TextEditingController(); return Column(crossAxisAlignment: CrossAxisAlignment.stretch, children: [Text('RONDA ${round.number}', style: const TextStyle(fontSize: 20)), const SizedBox(height: 18), Text('“${round.question.text}”', style: const TextStyle(fontSize: 28, fontWeight: FontWeight.w700)), const SizedBox(height: 18), TextField(controller: input, maxLength: 300, maxLines: 4, decoration: const InputDecoration(labelText: '¿Qué responderías?')), FilledButton(onPressed: () => controller.answer(input.text), child: const Text('GUARDAR RESPUESTA'))]); }
  @override void dispose() { nickname.dispose(); code.dispose(); super.dispose(); }
}
